### ISSUE TITLE
Chat view jumps to the first message in the channel history when a new peer joins

### ISSUE THREAD

**Issue by timgoeller** [cabal-club/cabal-desktop#246] opened 2020-05-16 11:54 UTC
When a new peer connects to a cabal, the screen reloads and jumps to the top of the channel the user is currently in. This also happens when a new peer joins while cabal is running in background.
Version: 5.0.4

**Comment by nikolaiwarner** [comment] 2020-06-07 20:50
@timgoeller this may have been fixed in the 5.1.0 release, can you try this release and see if the issue is solved?

**Comment by timgoeller** [comment] 2020-06-08 11:23
@nikolaiwarner It doesn't jump to the top anymore, but now it jumps to the bottom of the channel when a user joins or leaves :D

**Comment by shibacomputer** [comment] 2020-07-09 11:16
just fyi I can reproduce this bug on 6.0.4

**Comment by timgoeller** [comment] 2021-01-09 15:30
additionally to that, when a peer comes online, it seems like that cabal is also automatically made the focused cabal. in the gif, i'm running a client (in ram) than joins a caba;. upon connection my view in cabal desktop jumps to the cabal that the client just joined. 

it's likely that this is also solved by #287, but i thought i'd still add this for reference.

![rk2B46zoSo](https://user-images.githubusercontent.com/10633973/104095472-48cf0c00-5297-11eb-9c1f-d20767d20613.gif)

**Comment by nikolaiwarner** [comment] 2021-03-30 21:22
fixed in release 6.0.7!

**Closed by nikolaiwarner** 2021-03-30 21:22 UTC
Labels: bug
