### ISSUE TITLE
Connecting to the public chat with the desktop app somehow doesn't work

### ISSUE THREAD

**Issue by beingalink** [cabal-club/cabal-desktop#93] opened 2018-10-18 16:32 UTC
Only connecting with the cli shows the real current users in the list. The desktop app connects but somehow doesn't show the users currently present correctly.

**Comment by cblgh** [comment] 2018-10-18 16:34
The desktop app needs to be updated with the fix that is described here
https://github.com/cabal-club/cabal-core/issues/17

**Comment by dorkmo** [comment] 2018-10-19 01:03
@beingalink which version did you try? the one listed on releases is still at 1.0.4

**Comment by beingalink** [comment] 2018-10-19 04:44
@dorkmo the one linked on the homepage: 1.0.4

**Comment by nikolaiwarner** [comment] 2018-12-21 14:13
@filipdanic Thanks for trying it! Which version and platform did you try?

v1.0.8 is the latest and was released last night. I tried the mac and appimage builds from that release and it launched and worked as good as it does. Compiling from source should also usually work.

**Comment by filipdanic** [comment] 2018-12-21 14:20
Downloaded the app this morning, the About says: `Version 1.0.8 (1.0.8)`

**Comment by nikolaiwarner** [comment] 2018-12-21 14:23
@filipdanic ok! if you go to View > Toggle Developer Tools, then do you see any error messages in the log?

**Comment by filipdanic** [comment] 2018-12-21 14:35
No errors. I see Redux actions being logged and they seem sensible. If I try to add the same cabal, I get an error `cabal already exists`, which makes sense.

I posted a message at some point. I wonder if you see it on the chat at your end?

```
author: "filipdanic"
content: "Hey, folks! 👋"
key: "e5bfd769bca7f274c4012ad7f4600a10677611794ddbdff842ca5bab9203518f1545384136538"
time:1545384136538
type: "chat/text"
```

**Comment by dwblair** [comment] 2018-12-21 14:47
Hi All -- tanks for all your great work on developing and testing this!  Such exciting new tech ... 

@filipdanic -- I'm on a train with spotty / weird wifi, but for what it's worth I don't see your message using the terminal version of cabal -- though, perhaps your desktop isn't connected as a peer currently?

In case it's helpful, we've been experimenting with cabal at an urban hackerspace, and on a farm; we have a cabal 'peer' constantly running at our makerspace -- you can see if you can connect to it:

cabal://aff26da71f1d8113f947bb4e2f0b4b32f9f462c41f8b6f364eeabdba45a4123f

For my own testing, I've installed the terminal version of cabal on digitalocean, and that's been a somewhat useful way of assessing connections ...

**Comment by filipdanic** [comment] 2018-12-21 14:54
I’m not sure how one “connects as a peer”? I just installed the Mac OS desktop client and followed the instructions on the website. Sorry for not being able to provide more details.

**Comment by dwblair** [comment] 2018-12-21 15:13
Hi @filipdanic !

Good question -- I'm just learning about all this myself :)

Right now, I have a PC that is connected to a cabal -- i.e. it is running a cabal process (in this case, using the terminal app), with the following cabal address:

cabal://aff26da71f1d8113f947bb4e2f0b4b32f9f462c41f8b6f364eeabdba45a4123f

If you already have cabal-desktop open, you attempt to connect to this cabal by clicking on the '+' symbol towards the top left of the app, which I'm indicating with an arrow below:

![cabal_desktop_add](https://user-images.githubusercontent.com/639760/50348878-0e577280-0508-11e9-9c68-febe7fd50da7.png)

If all goes well, this should allow you to connect to my PC (which will then be an online 'peer' for that cabal, for you), and download the latest messages that are stored on my machine. 

Sorry if this isn't clear -- I might try to make a video this weekend with a walk-through (I'm not really a coder, but at least I can contribute a video, I guess :))

**Comment by filipdanic** [comment] 2018-12-21 15:32
That’s kind of what I did, clicked on the plus sign and then joined:

![image](https://user-images.githubusercontent.com/7009755/50349949-b9ceea00-053d-11e9-9068-7b39327a8c96.png)

And nothing.

**Comment by filipdanic** [comment] 2018-12-21 15:32
Now I actually installed the cli from npm and… it works. Not sure how it works, but thanks!

**Comment by dwblair** [comment] 2018-12-21 15:49
Ah, that's great! 

Quick question: are you finding that both the cli and cabal-desktop are working for you now?  Really useful to hear all of your testing experience here -- we're testing this tech out on off-grid farms and we're trying to figure out what configurations seem to be robust and which are still in-progress :)

Cheers!

**Comment by filipdanic** [comment] 2018-12-21 16:00
I can’t really tell since nobody seems to be chatting. If you could post something on the cabal chat I could see if the messages are coming in.

The cabal we set up here in the office worked for everyone without having to download the cli.

**Comment by nikolaiwarner** [comment] 2018-12-21 16:04
I've noticed that happening too. My guess is that the desktop (just mac?) cannot make the p2p connection beyond the local machine/local network. But the cli doesnt have that problem... So when they are both running, the desktop can locally peer with the cli and the cli forwards messages from the internet beyond.

**Comment by dwblair** [comment] 2018-12-21 16:08
@nikolaiwarner -- Ah, that makes sense to me -- (and in a way, that's pretty darn cool, that the forwarding works that way!)

@filipdanic I'll post some messages to cabal://e5bfd769bca7f274c4012ad7f4600a10677611794ddbdff842ca5bab9203518f1545384136538 right now ...

**Comment by filipdanic** [comment] 2018-12-21 16:08
Okay, I’ve just confirmed that the Desktop does not sync remote stuff unless I have the same channel open in my cli.

**Comment by dwblair** [comment] 2018-12-21 16:39
Yes, I can also confirm on Ubuntu 18.04.1:  cabal-desktop (1.0.8) doesn't sync with remote peers unless same cabal is connected via local cabal terminal cli.

**Comment by nikolaiwarner** [comment] 2018-12-21 16:40
Ugg yeah I just confirmed it on Ubuntu as well.... needs a cli instance running.

**Comment by dwblair** [comment] 2018-12-21 16:45
This is really useful -- thanks to you both -- now I understand better the pattern I was observing. Let me know how I can help out via testing?

(Aside: even if the desktop currently requires the cli to sync, I'm still very happy that I have an alternative to Slack! :))

**Comment by nikolaiwarner** [comment] 2018-12-21 16:46
This explains so much of the weirdness i've felt forever. I most often also have the cli open as well... so this explains why i see it work great sometimes and sometimes just nothing.

Perhaps it has to do with Electron since it's happening on all platforms.

**Comment by dwblair** [comment] 2018-12-21 16:48
Yes! Same here.  Super useful to know.

In case it's relevant, this is what I get when I start up the AppImage on my system -- I believe I've been receiving a similar message for the last few versions of cabal-desktop:

```
dwblair@110s:~$ ./cabal-desktop-1.0.8-linux-x86_64.AppImage 
Electron could not be found. No hard resets for you!
(electron) 'app.makeSingleInstance(cb)' is deprecated. Use 'app.requestSingleInstanceLock() and app.on('second-instance', cb)' instead.
```

**Comment by nikolaiwarner** [comment] 2018-12-21 16:49
Thanks @dwblair and @filipdanic! Let's synchronize on the current public cabal: cabal:// a1efbe73cb1499e6932b603e0a59341b4399f5c789bd6c5d7746888204265cc2

**Comment by williamtstanley** [comment] 2018-12-21 17:05
Definitely need an instance of cabal-cli running atm or the Desktop app is broken. Just to chime in confirmation.

**Comment by karissa** [comment] 2019-05-30 17:38
this is fixed now

**Closed by karissa** 2019-05-30 17:38 UTC

**Comment by todrobbins** [comment] 2019-06-11 14:43
@filipdanic, I saw [your other issue](cabal-club/cabal-club.github.io/issues/6). See the above 👆🏻

The new/current [public cabal](cabal://0201400f1aa2e3076a3f17f4521b2cc41e258c446cdaa44742afe6e1b9fd5f82) is working with [cabal-desktop 2.0.0](https://github.com/cabal-club/cabal-desktop/releases/tag/v2.0.0). Try it out and let me know how you get on!

**Comment by martinheidegger** [comment] 2019-06-11 18:14
Doesn't work for me. Can't chat.

**Comment by cblgh** [comment] 2019-06-11 19:23
@martinheidegger what platform? what cabal? are you behind a (corporate?) NAT? does the [cabal cli](https://github.com/cabal-club/cabal) work for you?

**Comment by todrobbins** [comment] 2019-06-11 19:38
Yes, more info would be great for debugging this, @martinheidegger!

**Comment by martinheidegger** [comment] 2019-06-11 23:38
Hmm, cabal 2.0.0 - seems like I had the wrong channel key. Now it works but I wonder what I did wrong a week back when I installed it on Mac.

**Comment by todrobbins** [comment] 2019-06-12 00:58
The public cabal key did change very recently.
